### ISSUE TITLE
Can't be run outside of scope?

### ISSUE THREAD

**Issue by dzpt** [dchevell/flask-executor#19]
Why you have to bind it to a route? 
`RuntimeError: This decorator can only be used at local scopes when a request context is on the stack.  For instance within view functions.`

**Comment by iedmrc** [comment]
Same here:
```
    "This decorator can only be used at local scopes "
RuntimeError: This decorator can only be used at local scopes when a request context is on the stack.  For instance within view functions.
```

**Comment by t4skforce** [comment]
You actually can run outside of a route. Ugly but works

```
with app.test_request_context():
    executor.submit(...)
```

**Comment by dchevell** [comment]
Wouldn't call that ugly, I'd call that the standard expectation for every Flask extension. Could add some kind of workaround parameter but there are enough "how do I run Flask-related things outside of a request context?" questions on the internet that I'm not convinced a bespoke solution is warranted.
