### ISSUE TITLE
race condition in tests for default_done_callbacks 

### ISSUE THREAD

**Issue by okke-formsma** [dchevell/flask-executor#25]
The default_done_callbacks are sometimes not executed. This can for example be seen in https://travis-ci.org/dchevell/flask-executor/jobs/590102443.

```python
def test_propagate_exception_callback(app, caplog):
    caplog.set_level(logging.ERROR)
    app.config['EXECUTOR_PROPAGATE_EXCEPTIONS'] = True
    executor = Executor(app)
    with pytest.raises(NameError):
        with app.test_request_context('/'):
            future = executor.submit(fail)
            assert propagate_exceptions_callback in future._done_callbacks # this may fail
            concurrent.futures.wait([future])
```

This is due to a race condition in Executor.submit. The function is submitted to the pool, after which the default_done_callbacks are added. If the thread executing the function runs before the callbacks are added, ~~they will never be executed~~ they are executed immediately and are not added to the _default_done_callbacks array. 

```python
class Executor(InstanceProxy, concurrent.futures._base.Executor):
    #...
    def submit(self, fn, *args, **kwargs):
        fn = self._prepare_fn(fn)
        future = self._self.submit(fn, *args, **kwargs)
        for callback in self._default_done_callbacks:
            future.add_done_callback(callback)
        return FutureProxy(future, self)
```

**Comment by dchevell** [comment]
I've fixed the test here, not sure whether there's a behavioural bug just because the callbacks _are_ run in this instance. The test referenced was a bit dodgy though
