### ISSUE TITLE
public vs private interface of FutureCollection

### ISSUE THREAD

**Issue by marksantcroos** [dchevell/flask-executor#28]
Hi,

Thanks for creating this module.

I've got a question about the FutureCollection object. I would like to have some inspection methods, which are currently private (_futures).

Is there a good reason not to expose the collection publicly so that I can iterate over them?

Regards,

Mark

**Comment by davidferguson** [comment]
I'd also like to be able to inspect the `_futures` object, primarily to see if a key exists in it.

**Comment by marksantcroos** [comment]
FYI: I ended up not using this module, as I required more specific semantics, i.e. different queues for concurrent and exclusive tasks.

Feel free to either close this issue or to keep it open to collect an answer for future generations.

**Comment by dchevell** [comment]
I'll close this for now, but @davidferguson may be interested in #35
