### ISSUE TITLE
Lack of tags for releases

### ISSUE THREAD

**Issue by GregoryLand** [dchevell/flask-executor#32]
I am attempting to build an Arch Linux package for this as a dependency for another project.  The lack of tags that correlate to the pypi releases makes producing this package more difficult than it should be.  If pypi releases are being made it is probably a good idea to have proper tags to match each release.

**Comment by dchevell** [comment]
Hey @GregoryLand - this is done, I'll set up an automation so that future releases are always tagged appropriately.
