### ISSUE TITLE
ProcessPool executor doesn't excute the function

### ISSUE THREAD

**Issue by Trick3r** [dchevell/flask-executor#33]
As in the topic said, when I try to use process pool from flask -exec it seems like process pull doesn't go into my function, it just awakes another thread and stuck like that, below is the example image that can tell you what I've faced

![image](https://user-images.githubusercontent.com/54097936/78236363-16bc9c80-7504-11ea-98db-57dc9ad9efb8.png)

![image](https://user-images.githubusercontent.com/54097936/78236431-2cca5d00-7504-11ea-9cdf-9fbc916823e7.png)
 
and this is the code for my flask-api.

import flask
from flask import request, jsonify, render_template, Flask
import nltk
from nltk import NaiveBayesClassifier as nbc
import dill
from pythainlp.tokenize import word_tokenize
from pythainlp.corpus import thai_stopwords
import codecs
from itertools import chain
import pickle
import copy
import mysql.connector
from flask_json import FlaskJSON, JsonError, json_response, as_json
import json
import concurrent.futures
from concurrent.futures import ThreadPoolExecutor
import time
from datetime import timedelta
import flask_executor
from flask_executor import Executor

app = flask.Flask(__name__)
app.config["DEBUG"] = True
app.config['JSON_AS_ASCII'] = False
app.config['EXECUTOR_TYPE'] = 'process'
executor = Executor(app)

def start_work(sentence,vocabulary,classifier):
    print("we are here")
    featurized_test_sentence = {i: (i in word_token_test(sentence.lower())) for i in vocabulary}
    print("let see the result")
    ans = classifier.prob_classify(featurized_test_sentence)
    result = max(ans.prob("pos"), ans.prob("neg"))
    print("Result:",result)

    y_pred = ans.max()

    print("Y predict is:",y_pred)
    return y_pred

@app.route('/api/v2/resources/classifier')
def my_form():
    return render_template('from_ex.html')

@app.route('/api/v2/resources/classifier', methods=["POST"])
def api_classifier():

    print("Recieve data successful_1")
    data = request.get_json(force=True) 
    print("Recieve data successful_2")
    word2 = data['words']
    if type(word2) is list:
        for sente in word2:
            word = sente
    else:
        word = word2
    print("data:", word)
    print("Recieve data successful_3")
    count = 0
    count_positive = 0
    count_negative = 0
    max_prob = []
    print("Start the multithreading process")
    starter = executor.submit(start_work,word,vocabulary,classifier)
    end_time = time.monotonic()
    print("end_time",timedelta(seconds=end_time - start_time))
    print("The result is:",starter.result())
    return jsonify(starter.result())

if the program is working successfully it will return (Neg, Pos or Neut) and print it out, but it look like the threads are not going into the function.

Any help would be appreciated.

**Comment by dchevell** [comment]
Closing, can't repro without a better quality bug report
