### ISSUE TITLE
Is flask-executor supported in a flask app running on gunicorn gevent worker

### ISSUE THREAD

**Issue by siva-ram** [dchevell/flask-executor#36]
Can I user flask-executor to concurrently call multiple slow running external apis in my flask code

**Comment by Eshaan7** [comment]
Yes. Those calls would then run asynchronously. You may want to [customize](https://flask-executor.readthedocs.io/en/latest/#configuration) the settings to either use `ThreadPoolExecutor` or `ProcessPoolExecutor`. The latter is what you would want for actual _parallelism_.

**Comment by dchevell** [comment]
Closing this out, the answer is indeed yes, but worth remembering that since gunicorn forks multiple processes any attempt to use things like `submit_stored` will yield unexpected results, as this is stored in-process rather than using an interprocess memory store

**Comment by hdeval1** [comment]
What would you recommend to use instead of submit_stored?
