### ISSUE TITLE
Case of multiple gunicorn workers

### ISSUE THREAD

**Issue by eshaan7** [dchevell/flask-executor#43]
Hi. I am the author of the package, [Flask-shell2http](https://github.com/eshaan7/Flask-Shell2HTTP). It is a REST wrapper over python's subprocess API using flask-executor for async background jobs.

#### Cross reference issue

Please go through https://github.com/eshaan7/Flask-Shell2HTTP/issues/24#issuecomment-936112153 for context.

#### Problem Description

The [`FutureCollection`](https://github.com/dchevell/flask-executor/blob/342a40644686722e594df3ed2e577f5575817af0/flask_executor/futures.py#L7) class is where the key-future maping is stored which is not shared between threads/gunicorn workers.

#### Possible Solution

Is there a way for flask-executor to support sharing of `FutureCollection` between threads/gunicorn workers ? Maybe make the FutureCollection swappable in case someone wants to use something like Redis for storage ?

**Comment by dchevell** [comment]
@eshaan7 this was never really intended to be a robust inter-process data store, ultimately you'd need something like Redis for that and at that point you should probably stop using this library and start using something like Celery or Dramatiq. I wouldn't be _entirely_ against adding some kind of adapter here or some flask-cache integration, but I'm wary of re-inventing better solutions, so would want to keep something like that to a pretty thin wrapper / interface. I know this is pretty old, I'll close this for now but feel free to reopen if you want to discuss more.

**Comment by nioncode** [comment]
Can you please add this limitation to the docs? I naively thought that this would 'just work', but was surprised to see that I got weird results from my `/status` method depending on which gunicorn worker handled the request.
