### ISSUE TITLE
Flask 2.2 breaks Executor

### ISSUE THREAD

**Issue by marban** [dchevell/flask-executor#44]
The recent Flask 2.2 release throws all kinds of context errors when submitting a job:
```
  File /site-packages/flask/ctx.py, line 256, in pop
    _cv_app.reset(self._cv_tokens.pop())
ValueError: <Token var=<ContextVar name='flask.app_ctx' at 0x7fb4152020b0> at 0x7fb4054b1f50> was created in a different Context
```

**Comment by ppepos** [comment]
I ran into the same issue. I managed to work around it by adding this config key:

```py
app.config['EXECUTOR_PUSH_APP_CONTEXT'] = True
```

Maybe this should be default?

Good luck to you.

**Comment by dchevell** [comment]
Hey folks

Do you want to give this a try: https://github.com/dchevell/flask-executor/pull/45

`pip install git+https://github.com/dchevell/flask-executor.git@fix-appcontext` in a test environment should give you something to try.

**Comment by christopherpickering** [comment]
Thanks @dchevell this fixed the problem for my app.

**Comment by florianstoffers** [comment]
Hi @dchevell,
unfortunately your solution did not solve the problem in our case. (with flask==2.2.2)
Had to downgrade to flask 2.0.1 again.

**Comment by christopherpickering** [comment]
what error did you get?

**Comment by florianstoffers** [comment]
The Error was: ValueError: <Token var=<ContextVar name='flask.request_ctx' at 0x7fb4152020b0> at 0x7fb4054b1f50> was created in a different Context

**Comment by 3pmsundayafternoon** [comment]
Hi @florianstoffers, were you able to fix this?
