### ISSUE TITLE
Function was created in a different context

### ISSUE THREAD

**Issue by ktangri** [dchevell/flask-executor#48]
I'm running a flask server on Ubuntu and getting a strange context issue when using executor.submit(FUNCTION, PARAMS...) to run a background job.

Initializing the executor as the docs specify
```
app = Flask(__name__)
executor = Executor(app)
```
I'm receiving the following trace:
```
Error on request:                                                          
Traceback (most recent call last):
  File "/home/ubuntu/lens-backend/env/lib/python3.10/site-packages/werkzeug/serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "/home/ubuntu/lens-backend/env/lib/python3.10/site-packages/werkzeug/serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "/home/ubuntu/lens-backend/env/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/lens-backend/env/lib/python3.10/site-packages/werkzeug/middleware/dispatcher.py", line 78, in __call__
    return app(environ, start_response)
  File "/home/ubuntu/lens-backend/env/lib/python3.10/site-packages/flask/app.py", line 2541, in wsgi_app
    ctx.pop(error) 
  File "/home/ubuntu/lens-backend/env/lib/python3.10/site-packages/flask/ctx.py", line 415, in pop
    app_ctx.pop(exc)
  File "/home/ubuntu/lens-backend/env/lib/python3.10/site-packages/flask/ctx.py", line 256, in pop
    _cv_app.reset(self._cv_tokens.pop())
ValueError: <Token var=<ContextVar name='flask.app_ctx' at 0x7f4d54a74d60> at 0x7f4d51e3dc40> was created in a different Context
```
Any idea what the issue could be?

**Comment by dchevell** [comment]
What version of flask- executor? Can you provide an example of a function you’re submitting that reproduces this?

**Comment by ktangri** [comment]
I'm using Flask-Executor 0.10.0, besides very basic python code here are the main components of the function:

```
# Normal Flask endpoint
@app.route('/endpoint', method=["POST"])
@authorization_middleware
def endpoint():
    if request.method == "POST":
        user = jwt.decode(FROM_USER_COOKIES)
        body = request.json
        params = body['params']
        # Not including all params for brevity
        executor.submit(background_job, params)
        return SOME_RESPONSE
```

```
# Background function
def background_job(params, oauth_token, oauth_secret):
    # Some AWS database writes
    s3 = boto3.resource('s3')
    dynamo_table = dynamodb.Table("Table Name")
    DATABASE WRITES

    # Oauth authenticated api request
    consumer = oauth.Consumer(app.config['KEY'], app.config['SECRET_KEY'])
    real_token = oauth.Token(oauth_token, oauth_secret)
    real_client = oauth.Client(consumer, real_token)
    resp, content = real_client.request(URL, method='POST', body=json.dumps(params).encode('utf-8'), headers={'Content-Type': 'application/json'})
```

What's also very strange about this issue is I only see this issue on the first request sent to /endpoint. It will return a 500 response, but will successfully execute the code in background_job. After the first request, it seems to function fine without any errors as far as I've seen

**Comment by RangerWolf** [comment]
> I'm using Flask-Executor 0.10.0, besides very basic python code here are the main components of the function:
> 
> ```
> # Normal Flask endpoint
> @app.route('/endpoint', method=["POST"])
> @authorization_middleware
> def endpoint():
>     if request.method == "POST":
>         user = jwt.decode(FROM_USER_COOKIES)
>         body = request.json
>         params = body['params']
>         # Not including all params for brevity
>         executor.submit(background_job, params)
>         return SOME_RESPONSE
> ```
> 
> ```
> # Background function
> def background_job(params, oauth_token, oauth_secret):
>     # Some AWS database writes
>     s3 = boto3.resource('s3')
>     dynamo_table = dynamodb.Table("Table Name")
>     DATABASE WRITES
> 
>     # Oauth authenticated api request
>     consumer = oauth.Consumer(app.config['KEY'], app.config['SECRET_KEY'])
>     real_token = oauth.Token(oauth_token, oauth_secret)
>     real_client = oauth.Client(consumer, real_token)
>     resp, content = real_client.request(URL, method='POST', body=json.dumps(params).encode('utf-8'), headers={'Content-Type': 'application/json'})
> ```
> 
> What's also very strange about this issue is I only see this issue on the first request sent to /endpoint. It will return a 500 response, but will successfully execute the code in background_job. After the first request, it seems to function fine without any errors as far as I've seen

hi, from this post: https://emasquil.github.io/posts/multithreading-boto3/
`TL;DR clients are threadsafe but sessions and resources are not.`

may be you need to do this according to AWS document: https://boto3.amazonaws.com/v1/documentation/api/1.14.31/guide/session.html#multithreading-or-multiprocessing-with-sessions
```python
import boto3
import boto3.session
import threading

class MyTask(threading.Thread):
    def run(self):
        # Here we create a new session per thread
        session = boto3.session.Session()

        # Next, we create a resource client using our thread's session object
        s3 = session.resource('s3')

        # Put your thread-safe code here
```

**Comment by dchevell** [comment]
^ From the above it sounds like this might be Boto3 behaviour rather than related to this extension - having said that, could you also try using the latest `1.0.0` version rather than `0.1.0`? The latter is quite old.

**Comment by ktangri** [comment]
Thanks for the suggestions! The Boto3 session threading makes sense - I'll try this out and let you know if it resolves the issue

**Comment by ktangri** [comment]
Interestingly enough, it wasn't a Boto3 issue - I moved the creation of a session as part of each new thread and still saw the same issue. However, upgrading to 1.0.0 did fix the issue - again thanks for the help!

**Comment by RangerWolf** [comment]
Thanks for the response! Glad the issue is fixed. @ktangri But very curious how 1.0.0 fix the issue, how does it work?

**Comment by dchevell** [comment]
@RangerWolf this should enlighten: https://github.com/dchevell/flask-executor/issues/44
